/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   hex_color.h                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lkrabbe <lkrabbe@student.42heilbronn.de    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/02/18 05:54:23 by lkrabbe           #+#    #+#             */
/*   Updated: 2023/02/18 05:54:23 by lkrabbe          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#define MLX_COLOR_ALICEBLUE                   0xF0F8FFFF
#define MLX_COLOR_ANTIQUEWHITE                0xFAEBD7FF
#define MLX_COLOR_AQUA                        0x00FFFFFF
#define MLX_COLOR_AQUAMARINE                  0x7FFFD4FF
#define MLX_COLOR_AZURE                       0xF0FFFFFF
#define MLX_COLOR_BEIGE                       0xF5F5DCFF
#define MLX_COLOR_BISQUE                      0xFFE4C4FF
#define MLX_COLOR_BLACK                       0x000000FF
#define MLX_COLOR_BLANCHEDALMOND              0xFFEBCDFF
#define MLX_COLOR_BLUE                        0x0000FFFF
#define MLX_COLOR_BLUEVIOLET                  0x8A2BE2FF
#define MLX_COLOR_BROWN                       0xA52A2AFF
#define MLX_COLOR_BURLYWOOD                   0xDEB887FF
#define MLX_COLOR_CADETBLUE                   0x5F9EA0FF
#define MLX_COLOR_CHARTREUSE                  0x7FFF00FF
#define MLX_COLOR_CHOCOLATE                   0xD2691EFF
#define MLX_COLOR_CORAL                       0xFF7F50FF
#define MLX_COLOR_CORNFLOWERBLUE              0x6495EDFF
#define MLX_COLOR_CORNSILK                    0xFFF8DCFF
#define MLX_COLOR_CRIMSON                     0xDC143CFF
#define MLX_COLOR_CYAN                        0x00FFFFFF
#define MLX_COLOR_DARKBLUE                    0x00008BFF
#define MLX_COLOR_DARKCYAN                    0x008B8BFF
#define MLX_COLOR_DARKGOLDENROD               0xB8860BFF
#define MLX_COLOR_DARKGRAY                    0xA9A9A9FF
#define MLX_COLOR_DARKGREEN                   0x006400FF
#define MLX_COLOR_DARKKHAKI                   0xBDB76BFF
#define MLX_COLOR_DARKMAGENTA                 0x8B008BFF
#define MLX_COLOR_DARKOLIVEGREEN              0x556B2FFF
#define MLX_COLOR_DARKORANGE                  0xFF8C00FF
#define MLX_COLOR_DARKORCHID                  0x9932CCFF
#define MLX_COLOR_DARKRED                     0x8B0000FF
#define MLX_COLOR_DARKSALMON                  0xE9967AFF
#define MLX_COLOR_DARKSEAGREEN                0x8FBC8FFF
#define MLX_COLOR_DARKSLATEBLUE               0x483D8BFF
#define MLX_COLOR_DARKSLATEGRAY               0x2F4F4FFF
#define MLX_COLOR_DARKTURQUOISE               0x00CED1FF
#define MLX_COLOR_DARKVIOLET                  0x9400D3FF
#define MLX_COLOR_DEEPPINK                    0xFF1493FF
#define MLX_COLOR_DEEPSKYBLUE                 0x00BFFFFF
#define MLX_COLOR_DIMGRAY                     0x696969FF
#define MLX_COLOR_DODGERBLUE                  0x1E90FFFF
#define MLX_COLOR_FIREBRICK                   0xB22222FF
#define MLX_COLOR_FLORALWHITE                 0xFFFAF0FF
#define MLX_COLOR_FORESTGREEN                 0x228B22FF
#define MLX_COLOR_FUCHSIA                     0xFF00FFFF
#define MLX_COLOR_GAINSBORO                   0xDCDCDCFF
#define MLX_COLOR_GHOSTWHITE                  0xF8F8FFFF
#define MLX_COLOR_GOLD                        0xFFD700FF
#define MLX_COLOR_GOLDENROD                   0xDAA520FF
#define MLX_COLOR_GRAY                        0x808080FF
#define MLX_COLOR_GREEN                       0x008000FF
#define MLX_COLOR_GREENYELLOW                 0xADFF2FFF
#define MLX_COLOR_HONEYDEW                    0xF0FFF0FF
#define MLX_COLOR_HOTPINK                     0xFF69B4FF
#define MLX_COLOR_INDIANRED                   0xCD5C5CFF
#define MLX_COLOR_INDIGO                      0x4B0082FF
#define MLX_COLOR_IVORY                       0xFFFFF0FF
#define MLX_COLOR_KHAKI                       0xF0E68CFF
#define MLX_COLOR_LAVENDER                    0xE6E6FAFF
#define MLX_COLOR_LAVENDERBLUSH               0xFFF0F5FF
#define MLX_COLOR_LAWNGREEN                   0x7CFC00FF
#define MLX_COLOR_LEMONCHIFFON                0xFFFACDFF
#define MLX_COLOR_LIGHTBLUE                   0xADD8E6FF
#define MLX_COLOR_LIGHTCORAL                  0xF08080FF
#define MLX_COLOR_LIGHTCYAN                   0xE0FFFFFF
#define MLX_COLOR_LIGHTGOLDENRODYELLOW        0xFAFAD2FF
#define MLX_COLOR_LIGHTGRAY                   0xD3D3D3FF
#define MLX_COLOR_LIGHTGREEN                  0x90EE90FF
#define MLX_COLOR_LIGHTPINK                   0xFFB6C1FF
#define MLX_COLOR_LIGHTSALMON                 0xFFA07AFF
#define MLX_COLOR_LIGHTSEAGREEN               0x20B2AAFF
#define MLX_COLOR_LIGHTSKYBLUE                0x87CEFAFF
#define MLX_COLOR_LIGHTSLATEGRAY              0x778899FF
#define MLX_COLOR_LIGHTSTEELBLUE              0xB0C4DEFF
#define MLX_COLOR_LIGHTYELLOW                 0xFFFFE0FF
#define MLX_COLOR_LIME                        0x00FF00FF
#define MLX_COLOR_LIMEGREEN                   0x32CD32FF
#define MLX_COLOR_LINEN                       0xFAF0E6FF
#define MLX_COLOR_MAGENTA                     0xFF00FFFF
#define MLX_COLOR_MAROON                      0x800000FF
#define MLX_COLOR_MEDIUMAQUAMARINE            0x66CDAAFF
#define MLX_COLOR_MEDIUMBLUE                  0x0000CDFF
#define MLX_COLOR_MEDIUMORCHID                0xBA55D3FF
#define MLX_COLOR_MEDIUMPURPLE                0x9370DBFF
#define MLX_COLOR_MEDIUMSEAGREEN              0x3CB371FF
#define MLX_COLOR_MEDIUMSLATEBLUE             0x7B68EEFF
#define MLX_COLOR_MEDIUMSPRINGGREEN           0x00FA9AFF
#define MLX_COLOR_MEDIUMTURQUOISE             0x48D1CCFF
#define MLX_COLOR_MEDIUMVIOLETRED             0xC71585FF
#define MLX_COLOR_MIDNIGHTBLUE                0x191970FF
#define MLX_COLOR_MINTCREAM                   0xF5FFFAFF
#define MLX_COLOR_MISTYROSE                   0xFFE4E1FF
#define MLX_COLOR_MOCCASIN                    0xFFE4B5FF
#define MLX_COLOR_NAVAJOWHITE                 0xFFDEADFF
#define MLX_COLOR_NAVY                        0x000080FF
#define MLX_COLOR_OLDLACE                     0xFDF5E6FF
#define MLX_COLOR_OLIVE                       0x808000FF
#define MLX_COLOR_OLIVEDRAB                   0x6B8E23FF
#define MLX_COLOR_ORANGE                      0xFFA500FF
#define MLX_COLOR_ORANGERED                   0xFF4500FF
#define MLX_COLOR_ORCHID                      0xDA70D6FF
#define MLX_COLOR_PALEGOLDENROD               0xEEE8AAFF
#define MLX_COLOR_PALEGREEN                   0x98FB98FF
#define MLX_COLOR_PALETURQUOISE               0xAFEEEEFF
#define MLX_COLOR_PALEVIOLETRED               0xDB7093FF
#define MLX_COLOR_PAPAYAWHIP                  0xFFEFD5FF
#define MLX_COLOR_PEACHPUFF                   0xFFDAB9FF
#define MLX_COLOR_PERU                        0xCD853FFF
#define MLX_COLOR_PINK                        0xFFC0CBFF
#define MLX_COLOR_PLUM                        0xDDA0DDFF
#define MLX_COLOR_POWDERBLUE                  0xB0E0E6FF
#define MLX_COLOR_PURPLE                      0x800080FF
#define MLX_COLOR_REBECCAPURPLE               0x663399FF
#define MLX_COLOR_RED                         0xFF0000FF
#define MLX_COLOR_ROSYBROWN                   0xBC8F8FFF
#define MLX_COLOR_ROYALBLUE                   0x4169E1FF
#define MLX_COLOR_SADDLEBROWN                 0x8B4513FF
#define MLX_COLOR_SALMON                      0xFA8072FF
#define MLX_COLOR_SANDYBROWN                  0xF4A460FF
#define MLX_COLOR_SEAGREEN                    0x2E8B57FF
#define MLX_COLOR_SEASHELL                    0xFFF5EEFF
#define MLX_COLOR_SIENNA                      0xA0522DFF
#define MLX_COLOR_SILVER                      0xC0C0C0FF
#define MLX_COLOR_SKYBLUE                     0x87CEEBFF
#define MLX_COLOR_SLATEBLUE                   0x6A5ACDFF
#define MLX_COLOR_SLATEGRAY                   0x708090FF
#define MLX_COLOR_SNOW                        0xFFFAFAFF
#define MLX_COLOR_SPRINGGREEN                 0x00FF7FFF
#define MLX_COLOR_STEELBLUE                   0x4682B4FF
#define MLX_COLOR_TAN                         0xD2B48CFF
#define MLX_COLOR_TEAL                        0x008080FF
#define MLX_COLOR_THISTLE                     0xD8BFD8FF
#define MLX_COLOR_TOMATO                      0xFF6347FF
#define MLX_COLOR_TURQUOISE                   0x40E0D0FF
#define MLX_COLOR_VIOLET                      0xEE82EEFF
#define MLX_COLOR_WHEAT                       0xF5DEB3FF
#define MLX_COLOR_WHITE                       0xFFFFFFFF
#define MLX_COLOR_WHITESMOKE                  0xF5F5F5FF
#define MLX_COLOR_YELLOW                      0xFFFF00FF
#define MLX_COLOR_YELLOWGREEN                 0x9ACD32FF
