#define MLX_COLOR_AliceBlue                   0xF0F8FFFF
#define MLX_COLOR_AntiqueWhite                0xFAEBD7FF
#define MLX_COLOR_Aqua                        0x00FFFFFF
#define MLX_COLOR_Aquamarine                  0x7FFFD4FF
#define MLX_COLOR_Azure                       0xF0FFFFFF
#define MLX_COLOR_Beige                       0xF5F5DCFF
#define MLX_COLOR_Bisque                      0xFFE4C4FF
#define MLX_COLOR_Black                       0x000000FF
#define MLX_COLOR_BlanchedAlmond              0xFFEBCDFF
#define MLX_COLOR_Blue                        0x0000FFFF
#define MLX_COLOR_BlueViolet                  0x8A2BE2FF
#define MLX_COLOR_Brown                       0xA52A2AFF
#define MLX_COLOR_BurlyWood                   0xDEB887FF
#define MLX_COLOR_CadetBlue                   0x5F9EA0FF
#define MLX_COLOR_Chartreuse                  0x7FFF00FF
#define MLX_COLOR_Chocolate                   0xD2691EFF
#define MLX_COLOR_Coral                       0xFF7F50FF
#define MLX_COLOR_CornflowerBlue              0x6495EDFF
#define MLX_COLOR_Cornsilk                    0xFFF8DCFF
#define MLX_COLOR_Crimson                     0xDC143CFF
#define MLX_COLOR_Cyan                        0x00FFFFFF
#define MLX_COLOR_DarkBlue                    0x00008BFF
#define MLX_COLOR_DarkCyan                    0x008B8BFF
#define MLX_COLOR_DarkGoldenRod               0xB8860BFF
#define MLX_COLOR_DarkGray                    0xA9A9A9FF
#define MLX_COLOR_DarkGreen                   0x006400FF
#define MLX_COLOR_DarkKhaki                   0xBDB76BFF
#define MLX_COLOR_DarkMagenta                 0x8B008BFF
#define MLX_COLOR_DarkOliveGreen              0x556B2FFF
#define MLX_COLOR_DarkOrange                  0xFF8C00FF
#define MLX_COLOR_DarkOrchid                  0x9932CCFF
#define MLX_COLOR_DarkRed                     0x8B0000FF
#define MLX_COLOR_DarkSalmon                  0xE9967AFF
#define MLX_COLOR_DarkSeaGreen                0x8FBC8FFF
#define MLX_COLOR_DarkSlateBlue               0x483D8BFF
#define MLX_COLOR_DarkSlateGray               0x2F4F4FFF
#define MLX_COLOR_DarkTurquoise               0x00CED1FF
#define MLX_COLOR_DarkViolet                  0x9400D3FF
#define MLX_COLOR_DeepPink                    0xFF1493FF
#define MLX_COLOR_DeepSkyBlue                 0x00BFFFFF
#define MLX_COLOR_DimGray                     0x696969FF
#define MLX_COLOR_DodgerBlue                  0x1E90FFFF
#define MLX_COLOR_FireBrick                   0xB22222FF
#define MLX_COLOR_FloralWhite                 0xFFFAF0FF
#define MLX_COLOR_ForestGreen                 0x228B22FF
#define MLX_COLOR_Fuchsia                     0xFF00FFFF
#define MLX_COLOR_Gainsboro                   0xDCDCDCFF
#define MLX_COLOR_GhostWhite                  0xF8F8FFFF
#define MLX_COLOR_Gold                        0xFFD700FF
#define MLX_COLOR_GoldenRod                   0xDAA520FF
#define MLX_COLOR_Gray                        0x808080FF
#define MLX_COLOR_Green                       0x008000FF
#define MLX_COLOR_GreenYellow                 0xADFF2FFF
#define MLX_COLOR_HoneyDew                    0xF0FFF0FF
#define MLX_COLOR_HotPink                     0xFF69B4FF
#define MLX_COLOR_IndianRed                   0xCD5C5CFF
#define MLX_COLOR_Indigo                      0x4B0082FF
#define MLX_COLOR_Ivory                       0xFFFFF0FF
#define MLX_COLOR_Khaki                       0xF0E68CFF
#define MLX_COLOR_Lavender                    0xE6E6FAFF
#define MLX_COLOR_LavenderBlush               0xFFF0F5FF
#define MLX_COLOR_LawnGreen                   0x7CFC00FF
#define MLX_COLOR_LemonChiffon                0xFFFACDFF
#define MLX_COLOR_LightBlue                   0xADD8E6FF
#define MLX_COLOR_LightCoral                  0xF08080FF
#define MLX_COLOR_LightCyan                   0xE0FFFFFF
#define MLX_COLOR_LightGoldenRodYellow        0xFAFAD2FF
#define MLX_COLOR_LightGray                   0xD3D3D3FF
#define MLX_COLOR_LightGreen                  0x90EE90FF
#define MLX_COLOR_LightPink                   0xFFB6C1FF
#define MLX_COLOR_LightSalmon                 0xFFA07AFF
#define MLX_COLOR_LightSeaGreen               0x20B2AAFF
#define MLX_COLOR_LightSkyBlue                0x87CEFAFF
#define MLX_COLOR_LightSlateGray              0x778899FF
#define MLX_COLOR_LightSteelBlue              0xB0C4DEFF
#define MLX_COLOR_LightYellow                 0xFFFFE0FF
#define MLX_COLOR_Lime                        0x00FF00FF
#define MLX_COLOR_LimeGreen                   0x32CD32FF
#define MLX_COLOR_Linen                       0xFAF0E6FF
#define MLX_COLOR_Magenta                     0xFF00FFFF
#define MLX_COLOR_Maroon                      0x800000FF
#define MLX_COLOR_MediumAquaMarine            0x66CDAAFF
#define MLX_COLOR_MediumBlue                  0x0000CDFF
#define MLX_COLOR_MediumOrchid                0xBA55D3FF
#define MLX_COLOR_MediumPurple                0x9370DBFF
#define MLX_COLOR_MediumSeaGreen              0x3CB371FF
#define MLX_COLOR_MediumSlateBlue             0x7B68EEFF
#define MLX_COLOR_MediumSpringGreen           0x00FA9AFF
#define MLX_COLOR_MediumTurquoise             0x48D1CCFF
#define MLX_COLOR_MediumVioletRed             0xC71585FF
#define MLX_COLOR_MidnightBlue                0x191970FF
#define MLX_COLOR_MintCream                   0xF5FFFAFF
#define MLX_COLOR_MistyRose                   0xFFE4E1FF
#define MLX_COLOR_Moccasin                    0xFFE4B5FF
#define MLX_COLOR_NavajoWhite                 0xFFDEADFF
#define MLX_COLOR_Navy                        0x000080FF
#define MLX_COLOR_OldLace                     0xFDF5E6FF
#define MLX_COLOR_Olive                       0x808000FF
#define MLX_COLOR_OliveDrab                   0x6B8E23FF
#define MLX_COLOR_Orange                      0xFFA500FF
#define MLX_COLOR_OrangeRed                   0xFF4500FF
#define MLX_COLOR_Orchid                      0xDA70D6FF
#define MLX_COLOR_PaleGoldenRod               0xEEE8AAFF
#define MLX_COLOR_PaleGreen                   0x98FB98FF
#define MLX_COLOR_PaleTurquoise               0xAFEEEEFF
#define MLX_COLOR_PaleVioletRed               0xDB7093FF
#define MLX_COLOR_PapayaWhip                  0xFFEFD5FF
#define MLX_COLOR_PeachPuff                   0xFFDAB9FF
#define MLX_COLOR_Peru                        0xCD853FFF
#define MLX_COLOR_Pink                        0xFFC0CBFF
#define MLX_COLOR_Plum                        0xDDA0DDFF
#define MLX_COLOR_PowderBlue                  0xB0E0E6FF
#define MLX_COLOR_Purple                      0x800080FF
#define MLX_COLOR_RebeccaPurple               0x663399FF
#define MLX_COLOR_Red                         0xFF0000FF
#define MLX_COLOR_RosyBrown                   0xBC8F8FFF
#define MLX_COLOR_RoyalBlue                   0x4169E1FF
#define MLX_COLOR_SaddleBrown                 0x8B4513FF
#define MLX_COLOR_Salmon                      0xFA8072FF
#define MLX_COLOR_SandyBrown                  0xF4A460FF
#define MLX_COLOR_SeaGreen                    0x2E8B57FF
#define MLX_COLOR_SeaShell                    0xFFF5EEFF
#define MLX_COLOR_Sienna                      0xA0522DFF
#define MLX_COLOR_Silver                      0xC0C0C0FF
#define MLX_COLOR_SkyBlue                     0x87CEEBFF
#define MLX_COLOR_SlateBlue                   0x6A5ACDFF
#define MLX_COLOR_SlateGray                   0x708090FF
#define MLX_COLOR_Snow                        0xFFFAFAFF
#define MLX_COLOR_SpringGreen                 0x00FF7FFF
#define MLX_COLOR_SteelBlue                   0x4682B4FF
#define MLX_COLOR_Tan                         0xD2B48CFF
#define MLX_COLOR_Teal                        0x008080FF
#define MLX_COLOR_Thistle                     0xD8BFD8FF
#define MLX_COLOR_Tomato                      0xFF6347FF
#define MLX_COLOR_Turquoise                   0x40E0D0FF
#define MLX_COLOR_Violet                      0xEE82EEFF
#define MLX_COLOR_Wheat                       0xF5DEB3FF
#define MLX_COLOR_White                       0xFFFFFFFF
#define MLX_COLOR_WhiteSmoke                  0xF5F5F5FF
#define MLX_COLOR_Yellow                      0xFFFF00FF
#define MLX_COLOR_YellowGreen                 0x9ACD32FF